"""add request_payload_hash to investment_requests

Revision ID: 381da4338f07
Revises: 681e83d80026
Create Date: 2026-09-22 10:21:31.767788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381da4338f07'
down_revision: Union[str, Sequence[str], None] = '681e83d80026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate emits a bare NOT NULL add_column, which fails outright
    # against a table that already has rows (there's nothing to put in the
    # new column for them). A temporary server_default backfills existing
    # rows; dropping it afterward matches db/models.py's own
    # request_payload_hash, which has a Python-side default (mirroring
    # attempt_count's own client-side default="0"/0) but no server_default -
    # every future row goes through create_idempotent(), which always sets
    # a real hash explicitly, so no DB-level default should apply to it.
    op.add_column(
        'investment_requests',
        sa.Column('request_payload_hash', sa.String(length=64), nullable=False, server_default=''),
    )
    op.alter_column('investment_requests', 'request_payload_hash', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_requests', 'request_payload_hash')
    # ### end Alembic commands ###
