"""initial schema

Revision ID: a3d592816a15
Revises:
Create Date: 2026-09-19 14:29:53.054100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db.constants import JOB_STATUS_ENUM_NAME

# revision identifiers, used by Alembic.
revision: str = 'a3d592816a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Declared once at module level, with create_type=False, and created/dropped
# explicitly below - not left to op.create_table()'s default of creating the
# type inline. Autogenerate's default (create_type=True on a bare sa.Enum(...))
# never emits a matching DROP TYPE when a later migration drops the table, so
# downgrade base -> upgrade head fails with "type job_status already exists".
job_status_enum = postgresql.ENUM(
    "pending",
    "running",
    "completed",
    "failed",
    name=JOB_STATUS_ENUM_NAME,
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    job_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('investment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', job_status_enum, nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_investment_requests_attempt_count_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investment_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment_requests')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_investment_requests_user_id_idempotency_key'))
    )
    op.create_index('ix_investment_requests_active', 'investment_requests', ['status'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('ix_investment_requests_user_id_created_at', 'investment_requests', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('status', job_status_enum, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['investment_requests.id'], name=op.f('fk_agent_runs_request_id_investment_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('request_id', 'node_name', name=op.f('uq_agent_runs_request_id_node_name'))
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('total_listings', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('highest_listing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lowest_listing', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_properties', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['investment_requests.id'], name=op.f('fk_reports_request_id_investment_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('request_id', name=op.f('uq_reports_request_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('agent_runs')
    op.drop_index('ix_investment_requests_user_id_created_at', table_name='investment_requests')
    op.drop_index('ix_investment_requests_active', table_name='investment_requests', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('investment_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
    job_status_enum.drop(op.get_bind(), checkfirst=True)
