# schema/market_data.py
from pydantic import BaseModel, Field
from typing import List

class PropertyRecord(BaseModel):
    """Strict structural mirror of an individual real estate listing."""
    zpid: str = Field(..., description="Unique Zillow Property Identification token.")
    homeStatus: str = Field(..., description="Active market listing state (e.g., FOR_SALE).")
    address: str = Field(..., description="Complete legible geographic street mailing address.")
    city: str = Field(..., description="The city or municipality where the home resides.")
    state: str = Field(..., description="The two-letter state classification code.")
    zipcode: str = Field(..., description="The localized postal zip code.")
    price: float = Field(..., description="The current active listing price denominated in USD.")
    bedrooms: int = Field(..., description="Total count of dedicated bedroom spaces.")
    bathrooms: int = Field(..., description="Total count of dedicated bathroom spaces.")
    livingArea: float = Field(..., description="Total square footage or interior living space area.")

class RealEstateGatewayModel(BaseModel):
    """
        Strongly typed real estate telemetry containing raw math metrics,
        AI indicators, and the complete array of actual raw listings.
    """
    requested_location: str = Field(
        ..., description="The target geographic city, neighborhood, or zip code parameter queried."
    )
    total_listings: int = Field(
        ..., description="The total number of active property listings processed in this batch."
    )
    average_price: float = Field(
        ..., description="The arithmetic mean price derived across all matching active properties."
    )
    median_price: float = Field(
        ..., description="The middle value separating the higher half from the lower half of listings."
    )
    highest_listing: float = Field(
        ..., description="The highest active market price pulled from the regional dataset."
    )
    lowest_listing: float = Field(
        ..., description="The lowest active market price pulled from the regional dataset."
    )
    raw_properties: List[PropertyRecord] = Field(
        default_factory=list,
        description="The complete list of matching individual property records retrieved from the API gateway."
    )

class LLMMarketEvaluations(BaseModel):
    """
        AI EVALUATIONS MODEL
        The target schema for LLM structured output.
        Contains strictly the cognitive classifications.
    """
    inventory_velocity_tier: str = Field(
        ...,
        description="LLM evaluation of inventory movement based on listing volume. Choices: [STAGNANT, BALANCED, RUSH]."
    )
    pricing_dispersion_risk: str = Field(
        ...,
        description="LLM evaluation of neighborhood volatility based on pricing spreads. Choices: [STABLE, MODERATE, HIGH_VOLATILITY]."
    )

class MarketDataAgentOutput(BaseModel):
    """
    Final output contract returned by the Market Data Agent Node.
    """
    telemetry: RealEstateGatewayModel = Field(..., description="The untouched data payload returned from the API client.")
    evaluations: LLMMarketEvaluations = Field(..., description="The analytical payload generated by the LLM.")